apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openedx-ingress
  namespace: openedx
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "openedx-ip"
    networking.gke.io/managed-certificates: "openedx-ssl-cert"
    # networking.gke.io/v1beta1.FrontendConfig: "http-redirect"
    kubernetes.io/ingress.allow-http: "true"
spec:
  defaultBackend:
    service:
      name: cms
      port:
        number: 8000
  rules:
  - host: studio.openedx-stage.example.com
    http:
      paths:
      - backend:
          service:
            name: cms
            port:
              number: 8000
        path: /*
        pathType: ImplementationSpecific
  - host: openedx-stage.example.com
    http:
      paths:
      - backend:
          service:
            name: lms
            port:
              number: 8000
        path: /*
        pathType: ImplementationSpecific
  - host: apps.openedx-stage.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mfe
            port:
              number: 8002